version: "2.2"

services:
  postgres:
    image: postgres
    container_name: philister_api_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ./data/postgres:/var/lib/postgresql

  cache:
    image: redis:alpine
    container_name: philister_api_cache
    ports:
      - "6379:6379"
